Django/tuto/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
	path('', views.index, name='home'),
	path('<int:question_id>/', views.detail, name='detail'),
	path('<int:question_id>/results/', views.results, name='results'),
	path('<int:question_id>/vote/', views.vote, name='vote'),
]
# Descritos os caminhos e detalhes
# das telas que estão views
# Para acessar, por exemplo: é /polls/1/results

Django/tuto/tuto/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('polls/', include('polls.urls')),
	path('admin/', admin.site.urls),
]

Django/tuto/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):

        def __str__(self):
                return self.txt_pergunta
        # Adicionamos o esta def para quando perguntarmos ao
        # banco de dados ele responder algo diferente de 'Question object'

        def bool_foi_pub_hoje(self):
                return self.data_publicacao >= timezone.now() - datetime.timedelta(days=1)

        txt_pergunta    = models.CharField(max_length=200)
        data_publicacao = models.DateTimeField('date published')
        # O primeiro parâmetro "date published" é para 
        # tornar legível e mais fácil documentação

class Choice(models.Model):

        def __str__(self):
                return self.escolha

        pergunta = models.ForeignKey(Question, on_delete=models.CASCADE)
        escolha  = models.CharField(max_length=200)
        time_1   = models.CharField(max_length=5)
        time_2   = models.CharField(max_length=5)
        time_3   = models.CharField(max_length=5)
        time_4   = models.CharField(max_length=5)
        votos    = models.IntegerField(default=0)
        # A foreign key é usada para os tipos de relacionamentos
        # Muitos para um, muitos para muitos e um para um

Django/tuto/polls/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template import loader
from .models import Question

def index(request):
	ultima_questao_lista = Question.objects.order_by('data_publicacao')[:5]
	template = loader.get_template('polls/index.html')
	context = {
		'ultima_quest_lista': ultima_questao_lista,
	}
	return HttpResponse(template.render(context, request))

def detail(request, question_id):
	return HttpResponse('Visualizando a votação de: %s' %question_id)

def results(request, question_id):
	resultado = 'Você está olhando o resultado da votação de: %s'
	return HttpResponse(resultado % question_id)

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		escolhida = question.txt_pergunta.get(pk=request.POST['escolha'])
	except:
		# Exibir o formulário de votação
		return render(request, 'polls/detail.html', {
			'question': question,
			'error_message': 'Você não selecionou todas as partidas!'
		})
	else:
		escolhida += 1
		escolhida.save()
		# Sempre retorna uma HttpResponseRedirect depois de operação
		# de POST obter sucesso. Isso previne que o dado seja enviado 
		# duas vezes, caso usuário pressione botão voltar.
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

Django/tuto/polls/templates/polls/detail.html
<h1>{{ questao.txt_pergunta }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">>
        {% csrf_token %}
        {% for choice in questao.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.escolha }}</label>
        <br>
        {% endfor %}
        <input type="submit" value="Votar">
</form>

Django/tuto/polls/templates/polls/index.html
{% if ultima_quest_lista %}
<ul>
        {% for questao in ultima_quest_lista %}
        <li>
                <a href="/polls/{{ questao.id }}/">{{ questao.txt_pergunta }}</a>                
        </li>
        <li>
                <a href="/polls/{{ questao.id }}">{{ questao.txt_pergunta }}</a></li>
        </li>
        {% endfor %}
</ul>
{% else %}
<p>Sem perguntar disponíveis</p>
{% endif %}